language: node_js
node_js: '10'
sudo: required
script:
- echo $TRAVIS_COMMIT
env:
  global:
    secure: Pb1SWE2DrBgoXzk9DhdkdQleGe+xlKhNL7r2SMaOH7As4APfpUGTi53d00e9EYt+X/E0y61EKmWXJ9xrxDOWi7GE50nEGe3qqy4GlRhHaiBKVYaT7CtsTYMtFnL8gaCnjKAWc7JBTxS6GUBEkLZh4GI/qTE/6w+OqFxNRo0vbMbmUhKaakGxEUhDgKQxGA0E6sWPC/eZ+nQSJTs+ltAfOLw2V7o3ytqEOiZJ6s30K4XnbrafASs+l2hGhWngBQtnsZT6Js0rAEERWfSVZkkO40zEspLE86Cco1H3BzyfJ9u21D3xmhC4eOH2GNd8TgDtokNt9zMXePTnd6aBtM6CTJHlKnH3vHTcCWlI0AHGoUuGUCv6zU2g7l586h/swKMKr9MaRutGy5qJg+iiyx2QXQbOPRhZb2oCtL071Z1l5VJH+FxjNtSMDk0GJCiV2hCP9yZEdEjTDblM4gdAC2Z2vWOkWqVUUxAjskvIB3K6mvDzaSZZZgkiLBFma+6fVWMEcotVGxK2I+JyLi7aa41J8oTyx0QWxJBEdS3DCyDJmg+1tSSJOxl5Dl/igj6dexXKfU7dD20MLJkjqnWLevKGHt1/dDt5rgcDKx3izEn90nHkJZ8/dE/87oNAyH/AtaehQry5xNmk4YJv8qnzSlGQJ0BMJ4ZoQaqb6+FtQ8m8dLk=
